# docker-compose.yml

services:
  tourismwebapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    volumes:
      # Mount each project directory individually
      - ./Domain:/src/Domain
      - ./Application:/src/Application
      - ./Infrastructure:/src/Infrastructure
      - ./TourismAgency:/src/TourismAgency
      # Mount NuGet cache for faster restores
      - ~/.nuget:/root/.nuget
    depends_on:
      - tourismdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=tourismdb,1433;Database=TourismAgencyDB;User=sa;Password=YourPassword123!;TrustServerCertificate=True;
      - ConnectionStrings__Identity=Server=tourismdb,1433;Database=TourismIdentity;User=sa;Password=YourPassword123!;TrustServerCertificate=True;
      - Cors__AllowedOrigins=http://tourismclient:5173,http://localhost:5173

  tourismdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - tourismVolume:/var/opt/mssql
  tourismclient:
    build:
      context: ./TourismAgencyClient
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./TourismAgencyClient:/usr/src/app
      - app_node_modules:/usr/src/app/node_modules 
    environment:
      - VITE_API_URL=http://localhost:5050
    depends_on:
      - tourismwebapp


volumes:
  tourismVolume:
  app_node_modules: