# docker-compose.yml
version: '3.8'

services:
  tourismWebApp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./TourismAgency:/src/TourismAgency
      - ~/.nuget:/root/.nuget
    depends_on:
      - tourismDb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=localhost,1433;Database=TourismAgencyDB;User=sa;Password=YourPassword123!;

  tourismDb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - tourismVolume:/var/opt/mssql

volumes:
  tourismVolume:
