# docker-compose.yml

services:
  tourismwebapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    volumes:
      # Mount each project directory individually
      - ./Domain:/src/Domain
      - ./Application:/src/Application
      - ./Infrastructure:/src/Infrastructure
      - ./TourismAgency:/src/TourismAgency
      # Mount NuGet cache for faster restores
      - ~/.nuget:/root/.nuget
    depends_on:
      - tourismdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=tourismdb,1433;Database=TourismAgencyDB;User=sa;Password=YourPassword123!;TrustServerCertificate=True;
      - ConnectionStrings__Identity=Server=tourismdb,1433;Database=TourismIdentity;User=sa;Password=YourPassword123!;TrustServerCertificate=True;

  tourismdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - tourismVolume:/var/opt/mssql

volumes:
  tourismVolume: